networks:
  gnomebot:
    driver: bridge

services:
  gnomebot:
    build: .
    restart: always
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - './logs:/app/logs:rw'
    depends_on:
      - redis
    networks:
      - gnomebot
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - gnomebot
