version: '3'

services:
  gnomebot:
    container_name: 'gnomebot'
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - './src:/app/src:ro'
      - './logs:/app/logs:rw'
    command: yarn run dev
