networks:
  gnomebot:
    driver: bridge

services:
  dev:
    build: .
    restart: always
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    env_file:
      - .env
    volumes:
      - './src:/app/src:ro'
      - './.env:/app/.env:ro'
      - './logs:/app/logs:rw'
    command: yarn run dev
    depends_on:
      - redis
    networks:
      - gnomebot
  gnomebot:
    build: .
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - './logs:/app/logs:rw'
    depends_on:
      - redis
    networks:
      - gnomebot
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - gnomebot
