version: '3'

services:
  gnomebot-dev:
    environment:
      - NODE_ENV=development
    container_name: 'gnomebot_dev'
    extends:
      file: docker-compose.yml
      service: gnomebot
    volumes:
      - './src:/app/src:ro'
      - './logs:/app/logs:rw'
    command: yarn run dev
