version: '3'

services:
  gnomebot:
    container_name: 'gnomebot'
    build: .
  gnomebot-dev:
    container_name: 'gnomebot_dev'
    build: .
    volumes:
      - './src:/app/src'
    command: npm run dev
